### ISSUE TITLE
参数的意义

### ISSUE THREAD

**Issue by tianjun-world** [sunbingfeng/carto_metrics_reader#1]
你好，非常感谢你的代码，我是cartographer的小白，你可以帮忙解释下那些参数的意义么？我目前主要在做2d建图定位这一块，非常感谢

**Comment by sunbingfeng** [comment]
你好，

这个你需要好好看看代码。简单来说，cartographer会将其很多状态量，比如：约束数量、前后端计算耗时、线程池待处理队列长度等等，统统称作metrics，这些状态变量会方便我们对算法的运行情况有一个更定量的把控。cartographer_ros将这些所有的metrics收集起来，并开放了一个service去读取它们。

我写的这个工具就是定时去查询这些metrics，并通过图形化的界面显示出来。主要还是方便调试的目的。

供参考，由于不是issue，我就关闭了。 @tianjun-world
